### ISSUE TITLE
When trying to reuse objects, the unit value is overwritten.

### ISSUE THREAD

**Issue by imle** [kpn-iot/senml-c-library#3]
I have some code that looks like the following:

```c++
SenMLPack state(SENML_BASE_NAME_STATE);
SenMLBoolRecord sml_pump(F("pump"), SENML_UNIT_RATIO);

void checkStateChangesAndSendUpdateMessageIfNecessary(Task *me) {
  state.clear();

  if (last_states.pump != pump.isOn()) {
    state.add(&sml_pump);
    last_states.pump = pump.isOn();
    sml_pump.set(last_states.pump);
  }
  // the above if block is repeated with many objects

  if (state.getFirst() != nullptr) {
    StringStream sml_string_stream;
    state.toJson(&sml_string_stream);

  // Do something with the string here
  }
}
```

The first time a record gets added and converted to a json string there is no issue. However, all subsequent additions and string conversions thereafter result in a missing unit value.

If I add the below line to the if statement then it works fine and the unit occurs again.
```c++
sml_pump.setUnit(SENML_UNIT_RATIO);
```

Example expected output:
```json
[{"bn":"urn:ctrl:state:","n":"pump","u":"/","vb":true}]
```

Example output after first print:
```json
[{"bn":"urn:ctrl:state:","n":"pump","vb":true}]
```

I have confirmed that the unit is not set in the second loop with a few print statements but cannot understand why or from where. I have also confirmed that running `toJson` twice without calling clear works as expected and the first example output is printed twice.

**Comment by josephverburg** [comment]
Thanks for the report Imle, there seems to be a bug in the state.clear() method.  This is due to interplay between some internal functions. A workaround would be manually performing the clear correctly (from the last element to the first, instead of the current implementation first to last). 

An alternative is to use our new library https://github.com/kpn-iot/thingsml-c-library which is a largely rebuilt version of this library with many additions and improvements (and also a fix for this .clear problem). Migration to the new library should be fairly easy.

**Comment by imle** [comment]
Thanks for the info! I will see if I can make the switch. Feel free to close this.
